-- MySQL Script generated by MySQL Workbench
-- Mon Feb 22 14:44:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Capstone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Capstone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Capstone` DEFAULT CHARACTER SET utf8 ;
USE `Capstone` ;

-- -----------------------------------------------------
-- Table `Capstone`.`Lottery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Capstone`.`Lottery` ;

CREATE TABLE IF NOT EXISTS `Capstone`.`Lottery` (
  `idLottery` INT NOT NULL,
  `LotteryName` VARCHAR(45) NOT NULL,
  `University` VARCHAR(45) NULL,
  `StartTime` TIME NOT NULL,
  `timeBetween` INT NOT NULL,
  `numSlots` INT NOT NULL,
  `numTimes` INT NOT NULL,
  PRIMARY KEY (`idLottery`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capstone`.`Model Data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Capstone`.`Model Data` ;

CREATE TABLE IF NOT EXISTS `Capstone`.`Model Data` (
  `Room_id` INT NOT NULL,
  `Time` TIME NOT NULL,
  `Probabliity` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`Room_id`, `Time`),
  CONSTRAINT `fk_Model Data_Room1`
    FOREIGN KEY (`Room_id`)
    REFERENCES `Capstone`.`Room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capstone`.`Residence Hall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Capstone`.`Residence Hall` ;

CREATE TABLE IF NOT EXISTS `Capstone`.`Residence Hall` (
  `idResidence Hall` INT NOT NULL,
  `ResName` VARCHAR(45) NOT NULL,
  `Lottery_idLottery` INT NOT NULL,
  PRIMARY KEY (`idResidence Hall`),
  INDEX `fk_Residence Hall_Lottery1_idx` (`Lottery_idLottery` ASC) VISIBLE,
  CONSTRAINT `fk_Residence Hall_Lottery1`
    FOREIGN KEY (`Lottery_idLottery`)
    REFERENCES `Capstone`.`Lottery` (`idLottery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capstone`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Capstone`.`Room` ;

CREATE TABLE IF NOT EXISTS `Capstone`.`Room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `RoomName` VARCHAR(45) NOT NULL,
  `Occupancy` INT(10) NOT NULL,
  `Roomcol` VARCHAR(45) NOT NULL,
  `Residence Hall_idResidence Hall` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Room_Residence Hall_idx` (`Residence Hall_idResidence Hall` ASC) VISIBLE,
  CONSTRAINT `fk_Room_Residence Hall`
    FOREIGN KEY (`Residence Hall_idResidence Hall`)
    REFERENCES `Capstone`.`Residence Hall` (`idResidence Hall`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capstone`.`SampleData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Capstone`.`SampleData` ;

CREATE TABLE IF NOT EXISTS `Capstone`.`SampleData` (
  `Room_id` INT NOT NULL,
  `Year` YEAR(4) NOT NULL,
  `Time` TIME NOT NULL,
  `Slot` VARCHAR(45) NULL,
  INDEX `fk_SampleData_Room1_idx` (`Room_id` ASC) VISIBLE,
  PRIMARY KEY (`Room_id`, `Year`),
  CONSTRAINT `fk_SampleData_Room1`
    FOREIGN KEY (`Room_id`)
    REFERENCES `Capstone`.`Room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
